/* Car makes and models for the quote tool. Add or remove freely. */
const CARS = {
  "Abarth": ["500", "595", "695", "124 Spider"],
  "Alfa Romeo": ["Giulia", "Giulietta", "Stelvio", "Tonale", "MiTo", "159"],
  "Audi": ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q5", "Q7", "Q8", "TT", "e-tron", "RS3", "RS6"],
  "BMW": ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "6 Series", "7 Series", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z4", "i3", "i4", "iX"],
  "Citroën": ["C1", "C3", "C3 Aircross", "C4", "C4 Cactus", "C5 Aircross", "Berlingo", "DS3", "Dispatch", "Relay"],
  "Cupra": ["Formentor", "Leon", "Ateca", "Born"],
  "Dacia": ["Sandero", "Sandero Stepway", "Duster", "Jogger", "Logan", "Spring"],
  "DS": ["DS 3", "DS 3 Crossback", "DS 4", "DS 7", "DS 9"],
  "Fiat": ["500", "500X", "500L", "Panda", "Punto", "Tipo", "Doblo", "Ducato"],
  "Ford": ["Fiesta", "Focus", "Puma", "Kuga", "Mondeo", "EcoSport", "Galaxy", "S-Max", "C-Max", "B-Max", "Ka", "Mustang", "Ranger", "Transit", "Transit Custom", "Transit Connect", "Transit Courier", "Tourneo"],
  "Honda": ["Jazz", "Civic", "CR-V", "HR-V", "Accord", "e", "ZR-V"],
  "Hyundai": ["i10", "i20", "i30", "i40", "Kona", "Tucson", "Santa Fe", "Bayon", "Ioniq", "Ioniq 5", "Ioniq 6"],
  "Jaguar": ["XE", "XF", "XJ", "F-Pace", "E-Pace", "I-Pace", "F-Type"],
  "Jeep": ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler", "Avenger"],
  "Kia": ["Picanto", "Rio", "Ceed", "XCeed", "Stonic", "Niro", "Sportage", "Sorento", "Soul", "EV6", "Optima", "Venga"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Freelander", "Range Rover", "Range Rover Sport", "Range Rover Evoque", "Range Rover Velar"],
  "Lexus": ["CT", "IS", "ES", "NX", "RX", "UX", "LC", "RC"],
  "Mazda": ["Mazda2", "Mazda3", "Mazda6", "CX-3", "CX-30", "CX-5", "CX-60", "MX-5", "MX-30"],
  "Mercedes-Benz": ["A-Class", "B-Class", "C-Class", "CLA", "CLS", "E-Class", "S-Class", "GLA", "GLB", "GLC", "GLE", "GLS", "SLK", "SL", "Vito", "Sprinter", "EQA", "EQC"],
  "MG": ["MG3", "MG4", "MG5", "ZS", "HS", "GS"],
  "MINI": ["Hatch (3-door)", "Hatch (5-door)", "Convertible", "Clubman", "Countryman", "Paceman", "Electric"],
  "Mitsubishi": ["Mirage", "ASX", "Outlander", "Eclipse Cross", "L200", "Shogun"],
  "Nissan": ["Micra", "Note", "Juke", "Qashqai", "X-Trail", "Leaf", "Ariya", "Navara", "NV200", "370Z", "GT-R"],
  "Peugeot": ["107", "108", "208", "2008", "308", "3008", "408", "508", "5008", "Rifter", "Partner", "Expert", "Boxer"],
  "Polestar": ["Polestar 2", "Polestar 3", "Polestar 4"],
  "Porsche": ["911", "Boxster", "Cayman", "Cayenne", "Macan", "Panamera", "Taycan"],
  "Renault": ["Clio", "Captur", "Megane", "Kadjar", "Arkana", "Austral", "Scenic", "Zoe", "Twingo", "Kangoo", "Trafic", "Master"],
  "SEAT": ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco", "Alhambra", "Mii"],
  "Skoda": ["Citigo", "Fabia", "Scala", "Octavia", "Superb", "Kamiq", "Karoq", "Kodiaq", "Enyaq", "Yeti", "Rapid"],
  "Smart": ["ForTwo", "ForFour", "#1", "#3"],
  "SsangYong": ["Tivoli", "Korando", "Rexton", "Musso"],
  "Subaru": ["Impreza", "XV", "Forester", "Outback", "Levorg", "BRZ"],
  "Suzuki": ["Alto", "Celerio", "Ignis", "Swift", "Baleno", "Vitara", "S-Cross", "Jimny", "Across"],
  "Tesla": ["Model 3", "Model Y", "Model S", "Model X"],
  "Toyota": ["Aygo", "Aygo X", "Yaris", "Yaris Cross", "Corolla", "Auris", "Avensis", "C-HR", "RAV4", "Prius", "Land Cruiser", "Hilux", "Proace", "GR86", "Supra"],
  "Vauxhall": ["Corsa", "Astra", "Insignia", "Mokka", "Crossland", "Grandland", "Zafira", "Meriva", "Adam", "Viva", "Combo", "Vivaro", "Movano"],
  "Volkswagen": ["Up!", "Polo", "Golf", "ID.3", "ID.4", "ID.5", "T-Cross", "T-Roc", "Tiguan", "Touareg", "Passat", "Arteon", "Touran", "Sharan", "Scirocco", "Caddy", "Transporter", "Crafter"],
  "Volvo": ["V40", "V60", "V90", "S60", "S90", "XC40", "XC60", "XC90", "C40", "EX30"],
};
